apiVersion: v1
kind: Secret
metadata:
  name: accelerator-be-secret
type: Opaque
stringData:
  DEBUG_MODE: '1'
  IIASA_MICROSOFT_OPENID_ISSUER_WELL_KNOWN_CONF: 'https://login.microsoftonline.com/9b79b10b-0007-4e8a-b072-ad0c8cdc1aa5/v2.0/.well-known/openid-configuration'
  JWT_SECRET_KEY: 'BXFQ3E2L44XP4='
  ALLOWED_ORIGINS: 'http://accelerator.iiasa.ac.at,https://accelerator.iiasa.ac.at'
  DATABASE_URL: 'postgresql://accelera_prod:asaedg0d@ldom005.iiasa.ac.at/accelerator_prod'
  INITIAL_S3_ENDPOINT: 'https://minio81.iiasa.ac.at:9000'
  INITIAL_S3_API_KEY: 'ac_accelerator_prod'
  INITIAL_S3_SECRET_KEY: '10KYZ60sazdfasdfasdf4yHgiHrIzlwa'
  INITIAL_S3_BUCKET_NAME: 'accelerator-prod'
  CELERY_BROKER_URL: 'amqp://accelerator:acc3zsdazsdfq-pubsub-service:5672/acceleratsazdfadive-jobs'
  SMTP_HOST: 'mail.disa.ac.at'
  SMTP_PORT: '25'
  SMTP_STARTTLS: '0'
  SMTP_AUTH_REQUIRED: '0'
  ACCELERATOR_EMAIL: 'accelerator@iiasa.ac.at'
  FRONTEND_URL: 'https://accelerator.iiasa.ac.at'